#!/bin/bash
#
# This script is intended to be executed via the EC2 User Data facility. If
# your instance has access to the Internet (via an Internet Gateway or NAT
# instance), you can source this script at instance creation time by providing
# the following user data:
#
#   #!/bin/bash
#   bash -c "$(curl -sL http://bit.ly/1eocBY6)"
#
# To read more about what this script is doing:
#
#   https://github.com/derekchiles/aws-env
#
# To read more about EC2 User Data:
#
#   https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
#

if [[ $EUID -ne 0 ]]; then
	echo "$0: This script must be run as root."
	exit 1
fi

get-metadata() {
    local __outvar="${1}"
    local key="${2}"

    value=$(curl -s ${METADATA_URL}/${key})
    eval $__outvar="${value}"
}

AWS_ENV_GIT_URL=https://github.com/derekchiles/aws-env
VUNDLE_GIT_URL=https://github.com/gmarik/Vundle.vim
EC2_USER_HOME=~ec2-user
AWS_ENV_HOME="${EC2_USER_HOME}/aws-env"

get-metadata instance_id instance-id

# RHEL seems to have trouble with the correct time at boot
service ntpdate restart

###############################################################################
#
# Install software packages
#
###############################################################################
yum update -y

yum install -y git gcc openssl-devel python python-devel screen figlet

easy_install pip
pip install awscli
 
###############################################################################
#
# Install aws-env
#
###############################################################################
cd ~ec2-user
sudo -u ec2-user git clone "${AWS_ENV_GIT_URL}" 
sudo -u ec2-user git clone "${VUNDLE_GIT_URL}" "${EC2_USER_HOME}/.vim/bundle/vundle"

sudo -u ec2-user ln -s "${AWS_ENV_HOME}/screen/screenrc" "${EC2_USER_HOME}/.screenrc"
sudo -u ec2-user ln -s "${AWS_ENV_HOME}/vim/vimrc" "${EC2_USER_HOME}/.vimrc"

echo ". ${AWS_ENV_HOME}/bin/ec2-init" >> "${EC2_USER_HOME}/.bashrc"

###############################################################################
#
# Configure Duo Security, if enabled (https://www.duosecurity.com)
#
###############################################################################
if [ $# -eq 2 ]; then
	LOGIN_DUO_CONF_BUCKET="$1"
	LOGIN_DUO_CONF_KEY="$2"
	
	bash "${AWS_ENV_HOME}/duo/configure-duo" "${LOGIN_DUO_CONF_BUCKET}" "${LOGIN_DUO_CONF_KEY}"
fi

###############################################################################
#
# Set the MOTD
#
###############################################################################
cat > /tmp/motd <<EOM
------------------------------------------------------------------------------
It won't hug you back!
EOM

sudo -u ec2-user figlet "${instance_id}" >> /tmp/motd

cat >> /tmp/motd <<EOM
------------------------------------------------------------------------------
EOM

cp /tmp/motd /etc/motd

