#!/bin/bash
#
# This script is intended to be executed via the EC2 User Data facility. If
# your instance has access to the Internet (via an Internet Gateway or NAT
# instance), you can source this script at instance creation time by providing
# the following user data:
#
#   #!/bin/bash
#   bash -c "$(curl -L http://bit.ly/1eocBY6)"
#
# To read more about what this script is doing:
#
#   https://github.com/derekchiles/aws-env
#
# To read more about EC2 User Data:
#
#   https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html
#

AWS_ENV_GIT_URL=https://github.com/derekchiles/aws-env
VUNDLE_GIT_URL=https://github.com/gmarik/Vundle.vim
EC2_USER_HOME=~ec2-user
AWS_ENV_HOME="${EC2_USER_HOME}/aws-env"

sudo yum update -y
sudo yum install -y git
sudo yum install -y gcc
sudo yum install openssl-devel

cd ~ec2-user
sudo -u ec2-user git clone "${AWS_ENV_GIT_URL}" 
sudo -u ec2-user git clone "${VUNDLE_GIT_URL}" ~/.vim/bundle/vundle

sudo -u ec2-user ln -s "${AWS_ENV_HOME}/screenrc" "${EC2_USER_HOME}/.screenrc"
sudo -u ec2-user ln -s "${AWS_ENV_HOME}/vimrc" "${EC2_USER_HOME}/.vimrc"

echo ". ${AWS_ENV_HOME}/bin/ec2-init" >> "${EC2_USER_HOME}/.bashrc"

