#!/bin/bash

DUO_UNIX_SRC_URL=https://dl.duosecurity.com/duo_unix-latest.tar.gz
DUO_PREFIX=/opt/duo_unix
LOGIN_DUO_CONF_BUCKET=s3.derekch.com
LOGIN_DUO_CONF_KEY=login_duo.conf

tmp_dir=$(mktemp -d /tmp/duo_unix.XXXXXX)
if [ $? -ne 0 ]; then
	echo "Unable to make temp dir, exiting."
	exit 1
fi

cd "${tmp_dir}"
curl -sLO "${DUO_UNIX_SRC_URL}"
tar xvfz duo_unix-latest.tar.gz

root_dir=$(find . -mindepth 1 -maxdepth 1 -type d)
cd "${root_dir}"

./configure --prefix=${DUO_PREFIX} && make && make install

aws s3api get-object \
	--bucket "${LOGIN_DUO_CONF_BUCKET}" \
	--key "${LOGIN_DUO_CONF_KEY}" \
	/etc/duo/login_duo.conf

echo "ForceCommand ${DUO_PREFIX}/sbin/login_duo" >> /etc/ssh/sshd_config
echo "PermitTunnel no" >> /etc/ssh/sshd_config
echo "AllowTcpForwarding no" >> /etc/ssh/sshd_config

